stages:
  - lint
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: "1"
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:dind
    command: ["--mtu=1450"]

lint_python:
  stage: lint
  image: python:3.8
  script:
    - pip3 install flake8
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=20 --max-line-length=127 --statistics

build_image:
  stage: build
  image: python:3.8
  script:
    - curl -Lo /tmp/docker.tgz https://get.docker.com/builds/Linux/x86_64/docker-17.05.0-ce.tgz && tar -xf /tmp/docker.tgz -C /usr/local && rm /tmp/docker.tgz && export PATH=/usr/local/docker:$PATH && export DOCKER_HOST=tcp://docker:2375
    - |
      slept=0
      while ! docker info &> /dev/null; do
        if [ $slept -ge 120 ]; then
          echo "docker didn't start after ${slept}s"
          exit 1
        fi
        sleep 1
        slept=$((slept + 1))
      done
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --cache-from $CI_REGISTRY_IMAGE:devel --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --build-arg BUILDKIT_INLINE_CACHE=1 -t $IMAGE .
    - |
      docker push $IMAGE
      if [ "$CI_COMMIT_REF_NAME" = master ]; then
        docker tag $IMAGE $CI_REGISTRY_IMAGE:latest
        docker push $CI_REGISTRY_IMAGE:latest
      fi

test:
  stage: test
  image: $IMAGE
  script:
    - python3 -m tests.tests
