S -> CLASSIFICATION_TASK | REGRESSION_TASK | TIME_SERIES_CLASSIFICATION_TASK | TIME_SERIES_FORECASTING_TASK | COMMUNITY_DETECTION_TASK | GRAPH_MATCHING_TASK | COLLABORATIVE_FILTERING_TASK | VERTEX_CLASSIFICATION_TASK | LINK_PREDICTION_TASK | OBJECT_DETECTION_TASK | SEMISUPERVISED_CLASSIFICATION_TASK | CLUSTERING_TASK | TEXT_CLASSIFICATION_TASK | IMAGE_CLASSIFICATION_TASK | AUDIO_CLASSIFICATION_TASK | TEXT_REGRESSION_TASK | IMAGE_REGRESSION_TASK | AUDIO_REGRESSION_TASK | LUPI_TASK | VIDEO_CLASSIFICATION_TASK | NA_TASK
CLASSIFICATION_TASK -> IMPUTATION ENCODERS FEATURE_SCALING FEATURE_SELECTION CLASSIFICATION
REGRESSION_TASK -> IMPUTATION ENCODERS FEATURE_SCALING FEATURE_SELECTION REGRESSION
TIME_SERIES_CLASSIFICATION_TASK -> 'd3m.primitives.data_transformation.time_series_to_list.DSBOX' 'd3m.primitives.feature_extraction.random_projection_timeseries_featurization.DSBOX' FEATURE_SCALING CLASSIFICATION
TIME_SERIES_FORECASTING_TASK ->  IMPUTATION FEATURE_SCALING TIME_SERIES_FORECASTING | FEATURE_SELECTION REGRESSION
COMMUNITY_DETECTION_TASK -> COMMUNITY_DETECTION | CLASSIFICATION_TASK
GRAPH_MATCHING_TASK -> GRAPH_MATCHING | CLASSIFICATION_TASK
COLLABORATIVE_FILTERING_TASK -> IMPUTATION ENCODERS FEATURE_SCALING COLLABORATIVE_FILTERING
VERTEX_CLASSIFICATION_TASK -> VERTEX_CLASSIFICATION | CLASSIFICATION_TASK
LINK_PREDICTION_TASK -> LINK_PREDICTION | CLASSIFICATION_TASK
OBJECT_DETECTION_TASK -> OBJECT_DETECTION
CLUSTERING_TASK -> IMPUTATION ENCODERS FEATURE_SCALING FEATURE_SELECTION CLUSTERING
SEMISUPERVISED_CLASSIFICATION_TASK -> IMPUTATION ENCODERS FEATURE_SELECTION CLASSIFICATION SEMISUPERVISED_CLASSIFICATION
LUPI_TASK -> ENCODERS IMPUTATION FEATURE_SCALING FEATURE_SELECTION CLASSIFICATION
TEXT_CLASSIFICATION_TASK -> NATURAL_LANGUAGE_PROCESSING FEATURE_SELECTION CLASSIFICATION | TEXT_CLASSIFIER
TEXT_REGRESSION_TASK -> NATURAL_LANGUAGE_PROCESSING FEATURE_SELECTION REGRESSION
IMAGE_CLASSIFICATION_TASK -> 'd3m.primitives.feature_extraction.image_transfer.DistilImageTransfer' CLASSIFICATION | 'd3m.primitives.data_transformation.dataframe_to_tensor.DSBOX' 'd3m.primitives.feature_extraction.resnet50_image_feature.DSBOX' CLASSIFICATION
IMAGE_REGRESSION_TASK -> 'd3m.primitives.feature_extraction.image_transfer.DistilImageTransfer' REGRESSION | 'd3m.primitives.data_transformation.dataframe_to_tensor.DSBOX' 'd3m.primitives.feature_extraction.resnet50_image_feature.DSBOX' REGRESSION
AUDIO_CLASSIFICATION_TASK -> 'd3m.primitives.feature_extraction.audio_transfer.DistilAudioTransfer' CLASSIFICATION
AUDIO_REGRESSION_TASK -> 'd3m.primitives.feature_extraction.audio_transfer.DistilAudioTransfer' REGRESSION
VIDEO_CLASSIFICATION_TASK -> 'd3m.primitives.feature_extraction.resnext101_kinetics_video_features.VideoFeaturizer' CLASSIFICATION
VIDEO_REGRESSION_TASK -> 'd3m.primitives.feature_extraction.resnext101_kinetics_video_features.VideoFeaturizer' REGRESSION
NA_TASK -> CLASSIFICATION_TASK | REGRESSION_TASK
ENCODERS -> TEXT_ENCODER CATEGORICAL_ENCODER DATETIME_ENCODER
IMPUTATION -> 'primitive_terminal' | 'E'
FEATURE_SELECTION -> 'primitive_terminal' | 'E'
FEATURE_SCALING -> 'primitive_terminal' | 'E'
CLASSIFICATION -> 'primitive_terminal'
REGRESSION -> 'primitive_terminal'
TIME_SERIES_CLASSIFICATION -> 'primitive_terminal'
TIME_SERIES_FORECASTING -> 'primitive_terminal'
COMMUNITY_DETECTION -> 'primitive_terminal'
GRAPH_MATCHING -> 'primitive_terminal'
COLLABORATIVE_FILTERING -> 'primitive_terminal'
VERTEX_CLASSIFICATION -> 'primitive_terminal'
LINK_PREDICTION -> 'primitive_terminal'
SEMISUPERVISED_CLASSIFICATION -> 'primitive_terminal'
CLUSTERING -> 'primitive_terminal'
OBJECT_DETECTION -> 'primitive_terminal'
CATEGORICAL_ENCODER -> 'primitive_terminal'
TEXT_ENCODER -> 'primitive_terminal'
TEXT_CLASSIFIER -> 'primitive_terminal'
DATETIME_ENCODER -> 'primitive_terminal'
NATURAL_LANGUAGE_PROCESSING -> 'primitive_terminal'