S -> CLASSIFICATION_TASK | REGRESSION_TASK | TIME_SERIES_CLASSIFICATION_TASK | TIME_SERIES_FORECASTING_TASK | NA_TASK
CLASSIFICATION_TASK -> DATA_CLEANING DATA_TRANSFORMATION CLASSIFICATION | DATA_CLEANING FEATURE_SELECTION CLASSIFICATION
REGRESSION_TASK -> DATA_CLEANING DATA_TRANSFORMATION REGRESSION
TIME_SERIES_CLASSIFICATION_TASK -> 'd3m.primitives.data_preprocessing.time_series_to_list.DSBOX' 'd3m.primitives.feature_extraction.random_projection_timeseries_featurization.DSBOX' CLASSIFICATION | TIME_SERIES_CLASSIFICATION
TIME_SERIES_FORECASTING_TASK -> 'd3m.primitives.data_cleaning.imputer.SKlearn' DATA_CLEANING DATA_TRANSFORMATION REGRESSION
NA_TASK -> CLASSIFICATION_TASK | REGRESSION_TASK
DATA_CLEANING -> DATA_CLEANING 'primitive_terminal'| 'primitive_terminal' | 'E'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'primitive_terminal'| 'primitive_terminal' | 'E'
DATA_PREPROCESSING -> 'primitive_terminal'
FEATURE_SELECTION -> 'primitive_terminal'
FEATURE_EXTRACTION -> 'primitive_terminal'
CLASSIFICATION -> 'primitive_terminal'
REGRESSION -> 'primitive_terminal'
TIME_SERIES_CLASSIFICATION -> 'primitive_terminal'
TIME_SERIES_FORECASTING -> 'primitive_terminal'