S -> CLASSIFICATION_TASK | REGRESSION_TASK
CLASSIFICATION_TASK -> DATA_CLEANING DATA_TRANSFORMATION CLASSIFICATION
REGRESSION_TASK -> DATA_CLEANING DATA_TRANSFORMATION REGRESSION
DATA_CLEANING -> DATA_CLEANING 'primitive_datacleaning'| 'primitive_datacleaning'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'primitive_datatransformation'| 'primitive_datatransformation'
CLASSIFICATION -> 'primitive_classification'
REGRESSION -> 'primitive_regression'