S -> CLASSIFICATION_TASK
S -> REGRESSION_TASK
CLASSIFICATION_TASK -> DATA_CLEANING DATA_TRANSFORMATION CLASSIFICATION
CLASSIFICATION_TASK -> DATA_CLEANING FEATURE_SELECTION CLASSIFICATION
REGRESSION_TASK -> DATA_CLEANING DATA_TRANSFORMATION REGRESSION
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.imputer.SKlearn'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.missing_indicator.SKlearn'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.imputer.SKlearn'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.missing_indicator.SKlearn'
DATA_CLEANING -> 'E'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.one_hot_encoder.SKlearn'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.ordinal_encoder.SKlearn'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.one_hot_encoder.SKlearn'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.ordinal_encoder.SKlearn'
DATA_TRANSFORMATION -> 'E'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.generic_univariate_select.SKlearn'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.select_fwe.SKlearn'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.select_percentile.SKlearn'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.variance_threshold.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.ada_boost.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.bagging.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.bernoulli_naive_bayes.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.decision_tree.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.dummy.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.extra_trees.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.gaussian_naive_bayes.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.gradient_boosting.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.k_neighbors.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.linear_discriminant_analysis.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.linear_svc.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.logistic_regression.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.mlp.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.multinomial_naive_bayes.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.nearest_centroid.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.passive_aggressive.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.quadratic_discriminant_analysis.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.random_forest.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.sgd.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.svc.SKlearn'
REGRESSION -> 'd3m.primitives.regression.ada_boost.SKlearn'
REGRESSION -> 'd3m.primitives.regression.ard.SKlearn'
REGRESSION -> 'd3m.primitives.regression.decision_tree.SKlearn'
REGRESSION -> 'd3m.primitives.regression.dummy.SKlearn'
REGRESSION -> 'd3m.primitives.regression.elastic_net.SKlearn'
REGRESSION -> 'd3m.primitives.regression.extra_trees.SKlearn'
REGRESSION -> 'd3m.primitives.regression.gaussian_process.SKlearn'
REGRESSION -> 'd3m.primitives.regression.gradient_boosting.SKlearn'
REGRESSION -> 'd3m.primitives.regression.k_neighbors.SKlearn'
REGRESSION -> 'd3m.primitives.regression.kernel_ridge.SKlearn'
REGRESSION -> 'd3m.primitives.regression.lars.SKlearn'
REGRESSION -> 'd3m.primitives.regression.lasso.SKlearn'
REGRESSION -> 'd3m.primitives.regression.lasso_cv.SKlearn'
REGRESSION -> 'd3m.primitives.regression.linear_svr.SKlearn'
REGRESSION -> 'd3m.primitives.regression.mlp.SKlearn'
REGRESSION -> 'd3m.primitives.regression.passive_aggressive.SKlearn'
REGRESSION -> 'd3m.primitives.regression.random_forest.SKlearn'
REGRESSION -> 'd3m.primitives.regression.ridge.SKlearn'
REGRESSION -> 'd3m.primitives.regression.sgd.SKlearn'
REGRESSION -> 'd3m.primitives.regression.svr.SKlearn'