S -> CLASSIFICATION_TASK
S -> REGRESSION_TASK
S -> TIME_SERIES_CLASSIFICATION_TASK
S -> TIME_SERIES_FORECASTING_TASK
S -> COMMUNITY_DETECTION_TASK
S -> GRAPH_MATCHING_TASK
S -> COLLABORATIVE_FILTERING_TASK
S -> VERTEX_NOMINATION_TASK
S -> LINK_PREDICTION_TASK
S -> OBJECT_DETECTION_TASK
S -> SEMISUPERVISED_CLASSIFICATION_TASK
S -> TEXT_CLASSIFICATION_TASK
S -> IMAGE_CLASSIFICATION_TASK
S -> AUDIO_CLASSIFICATION_TASK
S -> TEXT_REGRESSION_TASK
S -> IMAGE_REGRESSION_TASK
S -> AUDIO_REGRESSION_TASK
S -> NA_TASK
CLASSIFICATION_TASK -> DATA_CLEANING DATA_TRANSFORMATION CLASSIFICATION
CLASSIFICATION_TASK -> DATA_CLEANING FEATURE_SELECTION CLASSIFICATION
REGRESSION_TASK -> DATA_CLEANING DATA_TRANSFORMATION REGRESSION
TIME_SERIES_CLASSIFICATION_TASK -> 'd3m.primitives.data_preprocessing.time_series_to_list.DSBOX' 'd3m.primitives.feature_extraction.random_projection_timeseries_featurization.DSBOX' CLASSIFICATION
TIME_SERIES_CLASSIFICATION_TASK -> TIME_SERIES_CLASSIFICATION
TIME_SERIES_FORECASTING_TASK -> DATA_CLEANING DATA_TRANSFORMATION REGRESSION
COMMUNITY_DETECTION_TASK -> COMMUNITY_DETECTION
COMMUNITY_DETECTION_TASK -> CLASSIFICATION_TASK
GRAPH_MATCHING_TASK -> GRAPH_MATCHING
GRAPH_MATCHING_TASK -> CLASSIFICATION_TASK
COLLABORATIVE_FILTERING_TASK -> COLLABORATIVE_FILTERING
COLLABORATIVE_FILTERING_TASK -> REGRESSION_TASK
VERTEX_NOMINATION_TASK -> VERTEX_NOMINATION
VERTEX_NOMINATION_TASK -> CLASSIFICATION_TASK
LINK_PREDICTION_TASK -> LINK_PREDICTION
LINK_PREDICTION_TASK -> CLASSIFICATION_TASK
OBJECT_DETECTION_TASK -> 'd3m.primitives.feature_extraction.yolo.DSBOX'
SEMISUPERVISED_CLASSIFICATION_TASK -> DATA_CLEANING FEATURE_SELECTION SEMISUPERVISED_CLASSIFICATION
TEXT_CLASSIFICATION_TASK -> TEXT_PROCESSING CLASSIFICATION
IMAGE_CLASSIFICATION_TASK -> IMAGE_PROCESSING CLASSIFICATION
AUDIO_CLASSIFICATION_TASK -> CLASSIFICATION
TEXT_REGRESSION_TASK -> TEXT_PROCESSING REGRESSION
IMAGE_REGRESSION_TASK -> IMAGE_PROCESSING REGRESSION
AUDIO_REGRESSION_TASK -> REGRESSION
NA_TASK -> CLASSIFICATION_TASK
NA_TASK -> REGRESSION_TASK
TEXT_PROCESSING -> 'd3m.primitives.data_preprocessing.text_reader.DataFrameCommon' 'd3m.primitives.data_preprocessing.tfidf_vectorizer.SKlearn'
IMAGE_PROCESSING -> 'd3m.primitives.data_preprocessing.image_reader.DataFrameCommon' 'd3m.primitives.data_transformation.dataframe_to_ndarray.Common' 'd3m.primitives.feature_extraction.vgg16.Umich' 'd3m.primitives.data_transformation.ndarray_to_dataframe.Common'
AUDIO_PROCESSING -> 'd3m.primitives.data_preprocessing.audio_reader.BBN'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.imputer.SKlearn'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.missing_indicator.SKlearn'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.cleaning_featurizer.DSBOX'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.column_fold.DSBOX'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.column_type_profiler.Simon'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.data_cleaning.Datacleaning'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.label_encoder.DSBOX'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.tabular_extractor.Common'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.imputer.SKlearn'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.missing_indicator.SKlearn'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.cleaning_featurizer.DSBOX'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.column_fold.DSBOX'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.column_type_profiler.Simon'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.data_cleaning.Datacleaning'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.label_encoder.DSBOX'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.tabular_extractor.Common'
DATA_CLEANING -> 'E'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.one_hot_encoder.SKlearn'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.ordinal_encoder.SKlearn'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.add_semantic_types.DataFrameCommon'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.data_cleaning.DistilEnrichDates'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.data_cleaning.DistilReplaceSingletons'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.data_cleaning.DistilTimeSeriesReshaper'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.dataframe_to_list.Common'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.dataframe_to_ndarray.Common'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.datetime_field_compose.DataFrameCommon'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.encoder.DistilBinaryEncoder'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.encoder.DistilTextEncoder'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.horizontal_concat.DataFrameConcat'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.i_vector_extractor.BBN'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.imputer.DistilCategoricalImputer'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.ndarray_to_list.Common'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.normalize_column_references.Common'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.normalize_graphs.Common'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.one_hot_encoder.DistilOneHotEncoder'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.ravel.DataFrameRowCommon'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.remove_columns.DataFrameCommon'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.remove_duplicate_columns.DataFrameCommon'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.rename_duplicate_name.DataFrameCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.one_hot_encoder.SKlearn'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.ordinal_encoder.SKlearn'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.add_semantic_types.DataFrameCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.data_cleaning.DistilEnrichDates'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.data_cleaning.DistilReplaceSingletons'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.data_cleaning.DistilTimeSeriesReshaper'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.dataframe_to_list.Common'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.dataframe_to_ndarray.Common'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.datetime_field_compose.DataFrameCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.encoder.DistilBinaryEncoder'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.encoder.DistilTextEncoder'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.horizontal_concat.DataFrameConcat'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.i_vector_extractor.BBN'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.imputer.DistilCategoricalImputer'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.ndarray_to_list.Common'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.normalize_column_references.Common'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.normalize_graphs.Common'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.one_hot_encoder.DistilOneHotEncoder'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.ravel.DataFrameRowCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.remove_columns.DataFrameCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.remove_duplicate_columns.DataFrameCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.rename_duplicate_name.DataFrameCommon'
DATA_TRANSFORMATION -> 'E'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.binarizer.SKlearn'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.count_vectorizer.SKlearn'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.feature_agglomeration.SKlearn'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.max_abs_scaler.SKlearn'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.min_max_scaler.SKlearn'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.normalizer.SKlearn'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.nystroem.SKlearn'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.polynomial_features.SKlearn'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.quantile_transformer.SKlearn'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.random_trees_embedding.SKlearn'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.rbf_sampler.SKlearn'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.robust_scaler.SKlearn'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.standard_scaler.SKlearn'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.tfidf_vectorizer.SKlearn'
DATA_PREPROCESSING -> 'd3m.primitives.classification.ensemble_voting.DSBOX'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.channel_averager.BBN'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.csv_reader.BBN'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.csv_reader.DataFrameCommon'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.data_conversion.FairnessPreProcessing'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.dataframe_to_tensor.DSBOX'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.dataset_sample.Common'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.dataset_text_reader.DatasetTextReader'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.datetime_range_filter.DataFrameCommon'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.encoder.DSBOX'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.flatten.DataFrameCommon'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.greedy_imputation.DSBOX'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.horizontal_concat.DSBOX'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.image_reader.DataFrameCommon'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.iterative_regression_imputation.DSBOX'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.label_decoder.DataFrameCommon'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.label_encoder.DataFrameCommon'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.largest_connected_component.JHU'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.low_rank_imputer.Cornell'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.mean_imputation.DSBOX'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.numeric_range_filter.DataFrameCommon'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.one_hot_encoder.MakerCommon'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.one_hot_encoder.PandasCommon'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.random_sampling_imputer.BYU'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.regex_filter.DataFrameCommon'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.signal_dither.BBN'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.splitter.DSBOX'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.targets_reader.BBN'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.term_filter.DataFrameCommon'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.text_reader.DataFrameCommon'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.trecs.Umich'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.unary_encoder.DSBOX'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.unfold.DSBOX'
DATA_PREPROCESSING -> 'd3m.primitives.data_preprocessing.video_reader.DataFrameCommon'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.generic_univariate_select.SKlearn'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.select_fwe.SKlearn'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.select_percentile.SKlearn'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.variance_threshold.SKlearn'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.joint_mutual_information.AutoRPI'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.pca_features.Pcafeatures'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.rffeatures.Rffeatures'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.score_based_markov_blanket.RPI'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.simultaneous_markov_blanket.AutoRPI'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.kernel_pca.SKlearn'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.pca.SKlearn'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.audio_featurization.Umich'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.audio_transfer.DistilAudioTransfer'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.huber_pca.Cornell'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.i3d.Umich'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.image_transfer.DistilImageTransfer'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.inceptionV3_image_feature.DSBOX'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.l1_low_rank.L1LowRank'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.log_mel_spectrogram.Umich'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.multitable_featurization.DSBOX'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.pca_features.RandomizedPolyPCA'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.random_projection_timeseries_featurization.DSBOX'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.resnet50_image_feature.DSBOX'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.resnext101_kinetics_video_features.VideoFeaturizer'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.signal_mfcc.BBN'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.sparse_pca.RobustSparsePCA'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.sparse_pca.SparsePCA'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.tfidf_vectorizer.BBN'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.vgg16.Umich'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.vgg16_image_feature.DSBOX'
FEATURE_EXTRACTION -> 'd3m.primitives.feature_extraction.yolo.DSBOX'
CLASSIFICATION -> 'd3m.primitives.classification.ada_boost.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.bagging.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.bernoulli_naive_bayes.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.decision_tree.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.dummy.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.extra_trees.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.gaussian_naive_bayes.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.gradient_boosting.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.k_neighbors.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.linear_discriminant_analysis.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.linear_svc.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.logistic_regression.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.mlp.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.multinomial_naive_bayes.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.nearest_centroid.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.passive_aggressive.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.quadratic_discriminant_analysis.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.random_forest.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.sgd.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.svc.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.bert_classifier.DistilBertPairClassification'
CLASSIFICATION -> 'd3m.primitives.classification.cover_tree.Fastlvm'
CLASSIFICATION -> 'd3m.primitives.classification.gaussian_classification.JHU'
CLASSIFICATION -> 'd3m.primitives.classification.gaussian_classification.MeanBaseline'
CLASSIFICATION -> 'd3m.primitives.classification.general_relational_dataset.GeneralRelationalDataset'
CLASSIFICATION -> 'd3m.primitives.classification.light_gbm.DataFrameCommon'
CLASSIFICATION -> 'd3m.primitives.classification.lstm.DSBOX'
CLASSIFICATION -> 'd3m.primitives.classification.lupi_rf.LupiRFClassifier'
CLASSIFICATION -> 'd3m.primitives.classification.lupi_rfsel.LupiRFSelClassifier'
CLASSIFICATION -> 'd3m.primitives.classification.lupi_svm.LupiSvmClassifier'
CLASSIFICATION -> 'd3m.primitives.classification.mlp.BBN'
CLASSIFICATION -> 'd3m.primitives.classification.multilabel_classifier.DSBOX'
CLASSIFICATION -> 'd3m.primitives.classification.random_classifier.Test'
CLASSIFICATION -> 'd3m.primitives.classification.random_forest.DataFrameCommon'
CLASSIFICATION -> 'd3m.primitives.classification.search.Find_projections'
CLASSIFICATION -> 'd3m.primitives.classification.search_hybrid.Find_projections'
CLASSIFICATION -> 'd3m.primitives.classification.tensor_machines_binary_classification.TensorMachinesBinaryClassification'
CLASSIFICATION -> 'd3m.primitives.classification.tree_augmented_naive_bayes.BayesianInfRPI'
CLASSIFICATION -> 'd3m.primitives.classification.xgboost_dart.DataFrameCommon'
CLASSIFICATION -> 'd3m.primitives.classification.xgboost_gbtree.DataFrameCommon'
CLASSIFICATION -> 'd3m.primitives.learner.text_classifier.DistilTextClassifier'
REGRESSION -> 'd3m.primitives.regression.ada_boost.SKlearn'
REGRESSION -> 'd3m.primitives.regression.ard.SKlearn'
REGRESSION -> 'd3m.primitives.regression.decision_tree.SKlearn'
REGRESSION -> 'd3m.primitives.regression.dummy.SKlearn'
REGRESSION -> 'd3m.primitives.regression.elastic_net.SKlearn'
REGRESSION -> 'd3m.primitives.regression.extra_trees.SKlearn'
REGRESSION -> 'd3m.primitives.regression.gaussian_process.SKlearn'
REGRESSION -> 'd3m.primitives.regression.gradient_boosting.SKlearn'
REGRESSION -> 'd3m.primitives.regression.k_neighbors.SKlearn'
REGRESSION -> 'd3m.primitives.regression.kernel_ridge.SKlearn'
REGRESSION -> 'd3m.primitives.regression.lars.SKlearn'
REGRESSION -> 'd3m.primitives.regression.lasso.SKlearn'
REGRESSION -> 'd3m.primitives.regression.lasso_cv.SKlearn'
REGRESSION -> 'd3m.primitives.regression.linear_svr.SKlearn'
REGRESSION -> 'd3m.primitives.regression.mlp.SKlearn'
REGRESSION -> 'd3m.primitives.regression.passive_aggressive.SKlearn'
REGRESSION -> 'd3m.primitives.regression.random_forest.SKlearn'
REGRESSION -> 'd3m.primitives.regression.ridge.SKlearn'
REGRESSION -> 'd3m.primitives.regression.sgd.SKlearn'
REGRESSION -> 'd3m.primitives.regression.svr.SKlearn'
REGRESSION -> 'd3m.primitives.regression.corex_supervised.EchoLinear'
REGRESSION -> 'd3m.primitives.regression.cover_tree.Fastlvm'
REGRESSION -> 'd3m.primitives.regression.fast_lad.FastLAD'
REGRESSION -> 'd3m.primitives.regression.monomial.Test'
REGRESSION -> 'd3m.primitives.regression.owl_regression.Umich'
REGRESSION -> 'd3m.primitives.regression.rfm_precondition_ed_gaussian_krr.RFMPreconditionedGaussianKRR'
REGRESSION -> 'd3m.primitives.regression.rfm_precondition_ed_polynomial_krr.RFMPreconditionedPolynomialKRR'
REGRESSION -> 'd3m.primitives.regression.search_hybrid_numeric.Find_projections'
REGRESSION -> 'd3m.primitives.regression.search_numeric.Find_projections'
REGRESSION -> 'd3m.primitives.regression.tensor_machines_regularized_least_squares.TensorMachinesRegularizedLeastSquares'
REGRESSION -> 'd3m.primitives.regression.xgboost_gbtree.DataFrameCommon'
TIME_SERIES_CLASSIFICATION -> 'd3m.primitives.time_series_classification.convolutional_neural_net.LSTM_FCN'
TIME_SERIES_CLASSIFICATION -> 'd3m.primitives.time_series_classification.k_neighbors.Kanine'
TIME_SERIES_CLASSIFICATION -> 'd3m.primitives.time_series_classification.shapelet_learning.Shallot'
TIME_SERIES_FORECASTING -> 'd3m.primitives.time_series_forecasting.arima.DSBOX'
TIME_SERIES_FORECASTING -> 'd3m.primitives.time_series_forecasting.arima.Parrot'
TIME_SERIES_FORECASTING -> 'd3m.primitives.time_series_forecasting.rnn_time_series.DSBOX'
TIME_SERIES_FORECASTING -> 'd3m.primitives.time_series_forecasting.time_series_to_list.RelationalTimeseries'
TIME_SERIES_FORECASTING -> 'd3m.primitives.time_series_forecasting.vector_autoregression.VAR'
COMMUNITY_DETECTION -> 'd3m.primitives.classification.community_detection.CommunityDetection'
COMMUNITY_DETECTION -> 'd3m.primitives.community_detection.community_detection_parser.CommunityDetectionParser'
COMMUNITY_DETECTION -> 'd3m.primitives.data_transformation.community_detection.DistilCommunityDetection'
GRAPH_MATCHING -> 'd3m.primitives.data_transformation.seeded_graph_matcher.DistilSeededGraphMatcher'
GRAPH_MATCHING -> 'd3m.primitives.graph_matching.seeded_graph_matching.JHU'
GRAPH_MATCHING -> 'd3m.primitives.link_prediction.graph_matching_link_prediction.GraphMatchingLinkPrediction'
COLLABORATIVE_FILTERING -> 'd3m.primitives.collaborative_filtering.high_rank_imputer.Cornell'
COLLABORATIVE_FILTERING -> 'd3m.primitives.learner.collaborative_filtering_link_prediction.DistilCollaborativeFiltering'
COLLABORATIVE_FILTERING -> 'd3m.primitives.link_prediction.collaborative_filtering_link_prediction.CollaborativeFilteringLinkPrediction'
VERTEX_NOMINATION -> 'd3m.primitives.data_transformation.vertex_nomination.DistilVertexNomination'
VERTEX_NOMINATION -> 'd3m.primitives.vertex_nomination.spectral_graph_clustering.JHU'
VERTEX_NOMINATION -> 'd3m.primitives.vertex_nomination.spectral_vertex_nomination.JHU'
LINK_PREDICTION -> 'd3m.primitives.data_transformation.link_prediction.DistilLinkPrediction'
LINK_PREDICTION -> 'd3m.primitives.link_prediction.data_conversion.JHU'
LINK_PREDICTION -> 'd3m.primitives.link_prediction.link_prediction.LinkPrediction'
LINK_PREDICTION -> 'd3m.primitives.link_prediction.rank_classification.JHU'
SEMISUPERVISED_CLASSIFICATION -> 'd3m.primitives.semisupervised_classification.iterative_labeling.AutonBox'