S -> DATA_CLEANING DATA_TRANSFORMATION REGRESSION
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.cleaning_featurizer.DSBOX'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.column_fold.DSBOX'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.column_type_profiler.Simon'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.data_cleaning.Datacleaning'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.imputer.SKlearn'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.label_encoder.DSBOX'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.missing_indicator.SKlearn'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.tabular_extractor.Common'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.cleaning_featurizer.DSBOX'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.column_fold.DSBOX'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.column_type_profiler.Simon'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.data_cleaning.Datacleaning'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.imputer.SKlearn'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.label_encoder.DSBOX'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.missing_indicator.SKlearn'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.tabular_extractor.Common'
DATA_CLEANING -> 'E'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.add_semantic_types.DataFrameCommon'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.data_cleaning.DistilEnrichDates'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.data_cleaning.DistilReplaceSingletons'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.data_cleaning.DistilTimeSeriesReshaper'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.dataframe_to_list.Common'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.dataframe_to_ndarray.Common'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.datetime_field_compose.DataFrameCommon'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.encoder.DistilBinaryEncoder'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.encoder.DistilTextEncoder'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.horizontal_concat.DataFrameConcat'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.i_vector_extractor.BBN'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.imputer.DistilCategoricalImputer'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.ndarray_to_list.Common'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.normalize_column_references.Common'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.normalize_graphs.Common'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.one_hot_encoder.DistilOneHotEncoder'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.one_hot_encoder.SKlearn'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.ordinal_encoder.SKlearn'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.ravel.DataFrameRowCommon'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.remove_columns.DataFrameCommon'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.remove_duplicate_columns.DataFrameCommon'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.rename_duplicate_name.DataFrameCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.add_semantic_types.DataFrameCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.data_cleaning.DistilEnrichDates'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.data_cleaning.DistilReplaceSingletons'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.data_cleaning.DistilTimeSeriesReshaper'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.dataframe_to_list.Common'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.dataframe_to_ndarray.Common'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.datetime_field_compose.DataFrameCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.encoder.DistilBinaryEncoder'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.encoder.DistilTextEncoder'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.horizontal_concat.DataFrameConcat'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.i_vector_extractor.BBN'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.imputer.DistilCategoricalImputer'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.ndarray_to_list.Common'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.normalize_column_references.Common'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.normalize_graphs.Common'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.one_hot_encoder.DistilOneHotEncoder'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.one_hot_encoder.SKlearn'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.ordinal_encoder.SKlearn'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.ravel.DataFrameRowCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.remove_columns.DataFrameCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.remove_duplicate_columns.DataFrameCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.rename_duplicate_name.DataFrameCommon'
DATA_TRANSFORMATION -> 'E'
REGRESSION -> 'd3m.primitives.regression.ada_boost.SKlearn'
REGRESSION -> 'd3m.primitives.regression.ard.SKlearn'
REGRESSION -> 'd3m.primitives.regression.corex_supervised.EchoLinear'
REGRESSION -> 'd3m.primitives.regression.cover_tree.Fastlvm'
REGRESSION -> 'd3m.primitives.regression.decision_tree.SKlearn'
REGRESSION -> 'd3m.primitives.regression.dummy.SKlearn'
REGRESSION -> 'd3m.primitives.regression.elastic_net.SKlearn'
REGRESSION -> 'd3m.primitives.regression.extra_trees.SKlearn'
REGRESSION -> 'd3m.primitives.regression.fast_lad.FastLAD'
REGRESSION -> 'd3m.primitives.regression.gaussian_process.SKlearn'
REGRESSION -> 'd3m.primitives.regression.gradient_boosting.SKlearn'
REGRESSION -> 'd3m.primitives.regression.k_neighbors.SKlearn'
REGRESSION -> 'd3m.primitives.regression.kernel_ridge.SKlearn'
REGRESSION -> 'd3m.primitives.regression.lars.SKlearn'
REGRESSION -> 'd3m.primitives.regression.lasso.SKlearn'
REGRESSION -> 'd3m.primitives.regression.lasso_cv.SKlearn'
REGRESSION -> 'd3m.primitives.regression.linear_svr.SKlearn'
REGRESSION -> 'd3m.primitives.regression.mlp.SKlearn'
REGRESSION -> 'd3m.primitives.regression.monomial.Test'
REGRESSION -> 'd3m.primitives.regression.owl_regression.Umich'
REGRESSION -> 'd3m.primitives.regression.passive_aggressive.SKlearn'
REGRESSION -> 'd3m.primitives.regression.random_forest.SKlearn'
REGRESSION -> 'd3m.primitives.regression.rfm_precondition_ed_gaussian_krr.RFMPreconditionedGaussianKRR'
REGRESSION -> 'd3m.primitives.regression.rfm_precondition_ed_polynomial_krr.RFMPreconditionedPolynomialKRR'
REGRESSION -> 'd3m.primitives.regression.ridge.SKlearn'
REGRESSION -> 'd3m.primitives.regression.search_hybrid_numeric.Find_projections'
REGRESSION -> 'd3m.primitives.regression.search_numeric.Find_projections'
REGRESSION -> 'd3m.primitives.regression.sgd.SKlearn'
REGRESSION -> 'd3m.primitives.regression.svr.SKlearn'
REGRESSION -> 'd3m.primitives.regression.tensor_machines_regularized_least_squares.TensorMachinesRegularizedLeastSquares'
REGRESSION -> 'd3m.primitives.regression.xgboost_gbtree.DataFrameCommon'