S -> DATA_CLEANING DATA_TRANSFORMATION CLASSIFICATION
S -> DATA_CLEANING FEATURE_SELECTION CLASSIFICATION
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.cleaning_featurizer.DSBOX'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.column_fold.DSBOX'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.column_type_profiler.Simon'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.data_cleaning.Datacleaning'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.imputer.SKlearn'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.label_encoder.DSBOX'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.missing_indicator.SKlearn'
DATA_CLEANING -> DATA_CLEANING 'd3m.primitives.data_cleaning.tabular_extractor.Common'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.cleaning_featurizer.DSBOX'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.column_fold.DSBOX'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.column_type_profiler.Simon'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.data_cleaning.Datacleaning'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.imputer.SKlearn'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.label_encoder.DSBOX'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.missing_indicator.SKlearn'
DATA_CLEANING -> 'd3m.primitives.data_cleaning.tabular_extractor.Common'
DATA_CLEANING -> 'E'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.add_semantic_types.DataFrameCommon'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.data_cleaning.DistilEnrichDates'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.data_cleaning.DistilReplaceSingletons'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.data_cleaning.DistilTimeSeriesReshaper'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.dataframe_to_list.Common'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.dataframe_to_ndarray.Common'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.datetime_field_compose.DataFrameCommon'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.encoder.DistilBinaryEncoder'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.encoder.DistilTextEncoder'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.horizontal_concat.DataFrameConcat'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.i_vector_extractor.BBN'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.imputer.DistilCategoricalImputer'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.ndarray_to_list.Common'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.normalize_column_references.Common'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.normalize_graphs.Common'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.one_hot_encoder.DistilOneHotEncoder'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.one_hot_encoder.SKlearn'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.ordinal_encoder.SKlearn'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.ravel.DataFrameRowCommon'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.remove_columns.DataFrameCommon'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.remove_duplicate_columns.DataFrameCommon'
DATA_TRANSFORMATION -> DATA_TRANSFORMATION 'd3m.primitives.data_transformation.rename_duplicate_name.DataFrameCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.add_semantic_types.DataFrameCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.data_cleaning.DistilEnrichDates'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.data_cleaning.DistilReplaceSingletons'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.data_cleaning.DistilTimeSeriesReshaper'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.dataframe_to_list.Common'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.dataframe_to_ndarray.Common'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.datetime_field_compose.DataFrameCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.encoder.DistilBinaryEncoder'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.encoder.DistilTextEncoder'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.horizontal_concat.DataFrameConcat'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.i_vector_extractor.BBN'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.imputer.DistilCategoricalImputer'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.ndarray_to_list.Common'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.normalize_column_references.Common'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.normalize_graphs.Common'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.one_hot_encoder.DistilOneHotEncoder'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.one_hot_encoder.SKlearn'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.ordinal_encoder.SKlearn'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.ravel.DataFrameRowCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.remove_columns.DataFrameCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.remove_duplicate_columns.DataFrameCommon'
DATA_TRANSFORMATION -> 'd3m.primitives.data_transformation.rename_duplicate_name.DataFrameCommon'
DATA_TRANSFORMATION -> 'E'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.generic_univariate_select.SKlearn'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.joint_mutual_information.AutoRPI'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.pca_features.Pcafeatures'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.rffeatures.Rffeatures'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.score_based_markov_blanket.RPI'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.select_fwe.SKlearn'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.select_percentile.SKlearn'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.simultaneous_markov_blanket.AutoRPI'
FEATURE_SELECTION -> 'd3m.primitives.feature_selection.variance_threshold.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.ada_boost.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.bagging.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.bernoulli_naive_bayes.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.bert_classifier.DistilBertPairClassification'
CLASSIFICATION -> 'd3m.primitives.classification.cover_tree.Fastlvm'
CLASSIFICATION -> 'd3m.primitives.classification.decision_tree.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.dummy.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.extra_trees.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.gaussian_classification.JHU'
CLASSIFICATION -> 'd3m.primitives.classification.gaussian_classification.MeanBaseline'
CLASSIFICATION -> 'd3m.primitives.classification.gaussian_naive_bayes.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.general_relational_dataset.GeneralRelationalDataset'
CLASSIFICATION -> 'd3m.primitives.classification.gradient_boosting.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.k_neighbors.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.light_gbm.DataFrameCommon'
CLASSIFICATION -> 'd3m.primitives.classification.linear_discriminant_analysis.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.linear_svc.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.logistic_regression.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.lstm.DSBOX'
CLASSIFICATION -> 'd3m.primitives.classification.lupi_rf.LupiRFClassifier'
CLASSIFICATION -> 'd3m.primitives.classification.lupi_rfsel.LupiRFSelClassifier'
CLASSIFICATION -> 'd3m.primitives.classification.lupi_svm.LupiSvmClassifier'
CLASSIFICATION -> 'd3m.primitives.classification.mlp.BBN'
CLASSIFICATION -> 'd3m.primitives.classification.mlp.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.multilabel_classifier.DSBOX'
CLASSIFICATION -> 'd3m.primitives.classification.multinomial_naive_bayes.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.nearest_centroid.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.passive_aggressive.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.quadratic_discriminant_analysis.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.random_classifier.Test'
CLASSIFICATION -> 'd3m.primitives.classification.random_forest.DataFrameCommon'
CLASSIFICATION -> 'd3m.primitives.classification.random_forest.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.search.Find_projections'
CLASSIFICATION -> 'd3m.primitives.classification.search_hybrid.Find_projections'
CLASSIFICATION -> 'd3m.primitives.classification.sgd.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.svc.SKlearn'
CLASSIFICATION -> 'd3m.primitives.classification.tensor_machines_binary_classification.TensorMachinesBinaryClassification'
CLASSIFICATION -> 'd3m.primitives.classification.tree_augmented_naive_bayes.BayesianInfRPI'
CLASSIFICATION -> 'd3m.primitives.classification.xgboost_dart.DataFrameCommon'
CLASSIFICATION -> 'd3m.primitives.classification.xgboost_gbtree.DataFrameCommon'
CLASSIFICATION -> 'd3m.primitives.learner.text_classifier.DistilTextClassifier'